---
# 
# Install the packages, github and SQL server

# Install packages
- name: Install packages
  apt:
    - name: "{{ common_packages }}"
      state: latest

# Copy github repository
- include: copy_code.yml

# Set up SQL
- include: mysql.yml

...