---
# 
# Install the packages, github and SQL server
#- name: Starting DBApp
#  hosts: localhost
#  become_user: root
#  become: true
#  become_method: sudo


#  tasks:
    # Install packages
# Copy github repository
- include: copy_code.yml

# Set up SQL
- include: mysql.yml
...