---
#
# Set up the SQL Server, and build the databases

- name: Install packages
  apt:
    name: "{{ common_packages }}"
    state: latest

- name: Install python packages
  pip:
    name: "{{ pip_packages }}"

- name: Create Mysql configuration file
  template: src=my.cnf.j2 dest=/etc/my.cnf
  notify:
  - restart mysql

- name: Start Mysql Service
  service: name=mysqld state=started enabled=yes

- name: Create a new database with name bookstore
  mysql_db:
    name: bookstore
    state: import
    target: /home/cc/mySqlDB/bookDB.sql
    collation: utf8_unicode_ci

- name: Create a new database with name moviedb
  mysql_db:
    name: moviedb
    state: import
    target: /home/cc/mySqlDB/movieDB.sql
    collation: utf8_unicode_ci

#- name: Set username and password for mysql
#  mysql_user:
#    login_unix_socket: /var/run/mysqld/mysqld.sock
#    name: root
#    password: password
#    priv: *.*:ALL host='%'
#    state: present
...