---
#
# Script main to call the roles for the WebApp and DBServer. Really just defines
# variables and executes roles

- hosts: localhost  ## FIXME: change to web
  become_user: root
  become: true
  become_method: sudo

  vars:
    - path: https://github.com/doc-vu/phpMySQLapp.git

      ubuntu_php_packages:
        - libapache2-mod-php
        - php
        - php-fpm
        - php-mysql

      common_packages:
        - git
        - apache2
        - mysql-server
        - build-essential
        - python-pip

  roles:
    - WebApplication
    - DBApplication
...