---
#
# Script main to call the roles for the WebApp and DBServer. Really just defines
# variables and executes roles

- name: Starting WebApp
  hosts: webserver
  become_user: root
  become: true
  become_method: sudo

  gather_facts: no

  pre_tasks:
    - name: install python
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python)
    - name: install pip
      raw: sudo apt-get install -y python-dev python-pip
    - name: upgrade pip
      raw: pip install --upgrade pip
    - name: install ansible
      raw: sudo apt-get install -y ansible


  tasks:
    - include: copy_resources.yml

    - name: Add permissions properly to the private key
      raw: chmod 0600 /home/cc/.ssh/team5_keypair.pem


  vars:
    - path: https://github.com/doc-vu/phpMySQLapp.git

      ubuntu_php_packages:
        - libapache2-mod-php
        - php
        - php-fpm
        - php-mysql

      common_packages:
        - git
        - apache2
        - mysql-server
        - build-essential
        - python-pip

      mysql_port: 3306

      pip_packages:
        - PyMySQL
        #- libselinux-python
        #- libsemanage-python

  roles:
    - WebApplication

#- name: Connect to DB and run roles
#  hosts: dbserver
#  user: root
#  become: yes
#  become_method: sudo
#
#  pre_tasks:
#    - name: install python
#      raw: test -e /usr/bin/python || (apt -y update && apt install -y python)
#  
#  roles:
#    - DBApplication
...