---
#
# Copies the code necessary to set up the github repo

- name: Delete directory for the ww
  file:
    path: /var/www/html
    state: absent
   
- name: Create directory for the www
  file:
    path: /var/www/html
    state: directory
    mode: 0777

- name: Clone Github Repo (WB)
  git:
    repo: "{{ path }}"
    dest: /var/www/html/

## FIXME: these need to be local variables

## Grep IP's into index files
- name: Writing IP to books DB
  raw: sed -i -e 's/127.0.0.1/192.168.2.27/g' /var/www/html/books/includes/bookDatabase.php

- name: Writing IP to movies DB
  raw: sed -i -e 's/127.0.0.1/192.168.2.27/g' /var/www/html/movies/includes/movieDatabase.php 
...