---
#
# Installs the common packages necessary. Configures apache2.

- name: Install common packages
  apt:
    name: "{{ common_packages }}"
    state: latest

- name: enabled mod_rewrite
  apache2_module:
    name: rewrite
    state: present
  notify:
    - restart apache2
...