---
#
# Main script for deploying the front end webserver.


# First install common packages/apache2
- include: install_apache2.yml

# Install php and configure
- include: install_php.yml

## set up the github repository
- include: copy_code.yml
...