---
#
# Main script for deploying the front end webserver.

- name: Install packages
   apt:
     name: common_packages
     state: latest  # latest version

## set up the github repository and template? (maybe)
#- include: copy_code.yml

...